CREATE TABLE AMIGOS(
    NOME VARCHAR(30),
    IDADE INT(8),
    SEXO CHAR(1),
    ENDEREÇO VARCHAR(100)
);
INSERT INTO AMIGOS(NOME, IDADE, SEXO, ENDEREÇO) VALUES('ATHOS',12052005,'M','CASA DO CARALHO');
DESC AMIGOS;
SHOW TABLES;
SELECT NOME, IDADE FROM AMIGOS WHERE IDADE LIKE '%2005';
