CREATE DATABASE LIVRARIA;
USE LIVRARIA;
CREATE TABLE LIVROS(
    NOME_DO_LIVRO CHAR(30),
    NOME_DO_AUTOR CHAR(30),
    SEXO_DO_AUTOR CHAR(1),
    NUMERO_DE_PAGINAS INT(4),
    NOME_DA_EDITORA CHAR(30),
    VALOR_DO_LIVRO INT(3),
    ESTADO_DO_LIVRO CHAR(2),
    ANO_DE_PUBLICAÇÃO CHAR(8)
);
INSERT INTO LIVROS VALUES('PEQUENO PRINCIPE','O GRANDE REI','M',234,'CORTE REAL',234,'RS','11081984');
INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DO_LIVRO,ANO_DE_PUBLICAÇÃO) VALUES('O CORTIÇO','JOSÉ SARAMAGO','M',343,'PANINI',563,'SP','23052001');
INSERT INTO LIVROS VALUES('NARUTO','KISHIMOTO','F',1200,'SHONEM JUMP',124,'JP','12122012');
SELECT NOME_DO_LIVRO,ESTADO_DO_LIVRO FROM LIVROS WHERE SEXO_DO_AUTOR='M';
SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;
SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS WHERE SEXO_DO_AUTOR = 'F';
SELECT * FROM LIVROS WHERE ESTADO_DO_LIVRO='SP';